[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
uuid = { version = "1.16.0", features = ["v4"] }
